### ISSUE TITLE
Query regarding blank index

### ISSUE THREAD

**Issue by bhaswa** [iankur/ContextNet#3]
The blank index is being specified as the last element of the vocabulary [here](https://github.com/iankur/ContextNet/blob/master/train.py#L98). But while padding the label, 0 is being padded as the blank index [here](https://github.com/iankur/ContextNet/blob/master/model.py#L194). Can you please explain how this is being matched?

Also while [embedding](https://github.com/iankur/ContextNet/blob/master/model.py#L187) the labels, blank index is not being included. But the labels are being padded with an extra 0, which is the blank index I suppose. Can you explain this also?

**Comment by iankur** [comment]
Each sequence is padded with “0” at the beginning since this is the first symbol which is fed to RNN-T while decoding (similar to what we have in attention-based models). In contrast, blank symbol is never fed to the decoder but only predicted by the model. I would suggest you to take a look at the decoding process of transducer models as proposed in the paper.
